# Generated by Django 3.1.5 on 2021-04-07 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='last_name',
        ),
    ]
