# Generated by Django 3.1.5 on 2021-04-08 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_auto_20210408_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='alamat',
            field=models.CharField(default='Bogor', max_length=255),
        ),
    ]
