# Generated by Django 3.1.5 on 2021-04-09 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_profile_alamat'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status_nikah',
            field=models.CharField(default='belum', max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='alamat',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='profile',
            name='divisi',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jabatan',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='profile',
            name='jenis_kelamin',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='profile',
            name='profile_pic',
            field=models.ImageField(blank=True, default='profil.png', null=True, upload_to='profile_pics'),
        ),
    ]
